## Array Indexing

Elements in a numpy array can be accessed using _indexing_. Indexing is an opperation that pulls out a select set of values from an array. The _index_ of a value in an array is that value's location. There is a difference between the the value that is stored and the index or location of that value within an array. Take the following example. Remember that counting in Python starts at zero.

In [2]:
import numpy as np

a = np.array([2,4,6])

In the array above, there are three values stored: ```2```, ```4``` and ```6```. Each of these values has a different index. The value ```2``` has an index of 0. ```2``` is in the 0 location in the array. The value ```4``` has an index of ```1``` and the value ```6``` has an index of 2. A table summarizes this below:

| Index or Location | Value |
| --- | ---|
| 0 | ```2``` |
| 1 | ```4``` |
| 2 | ```6``` |

Individual values stored in array can be accessed using indexing. The general form is:

```
<value> = <array>[index]
```

Where ```<value>``` is the value store in the array, ```<array>``` is the array object name and ```[index]``` specifies the index or location of that value. Applied to our example above, the value 6 is stored at index 2.

In [3]:
import numpy as np

a = np.array([2,4,6])
value = a[2]
print(value)

6


### Multi-dimensional Array Indexing

Mulit-dimensional arrays are indexed as well. A simple 2-D array is defined by a list of lists.

In [5]:
import numpy as np

a = np.array([[2,3,4],[6,7,8]])
print(a)

[[2 3 4]
 [6 7 8]]


Values in a 2-D array can be accessed using the general notation below:

```
<value> = <array>[row,col]
```

Where ```<value>``` is the value pulled out of the 2-D array named ```<array```. ```[row,col]``` specifies the row and column index of the value. Remember that Python counting starts at 0, so the first row is row zero and the first column is column zero.

We can access the value ```8``` in the array above by calling the row and column index ```[1,2]``` for the 2nd row (rememeber row 0 is the first row) and the 3rd column (rememeber column 0 is the first column).


In [6]:
import numpy as np

a = np.array([[2,3,4],[6,7,8]])
value = a[1,2]
print(value)

8


### Assigning Values with Indexing

Array indexing can be used to access values in an array and they can also be used for _assigning_ values of an array. In order to assign a value to a particular index or location in an array, the following general form is used:

```
<array>[index] = <value>
```

Where ```<array>``` is the array object that value will be assigned to, ```[index]``` is the index or location the value will be put in and ```<value>``` is the value assigned to that location. 

If we want to put the value ```10``` into the third index or location of an array, it can be coded as follows:

In [8]:
import numpy as np
a = np.array([2,4,6])
a[2] = 10
print(a)

[ 2  4 10]


Values can also be assigned into 2-D arrays using the form

```
<array>[row,col] = <value>
```

An example is below:

In [10]:
import numpy as np

a = np.array([[2,3,4],[6,7,8]])
print(a)

a[1,2]=20
print(a)

[[2 3 4]
 [6 7 8]]
[[ 2  3  4]
 [ 6  7 20]]
