## Array Operations

Mathematical operations can be completed using numpy arrays. 

### Scalar Addition

Scalars can be added and subtracted from arrays and arrays can be added and subtrated from eachother:

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = a + 2
print(b)

[3 4 5]


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
c = a + b
print(c)

[3 6 9]


## Scalar Multiplication

Numpy arrays can be multiplied and divied by scalars:

In [4]:
import numpy as np

a = np.array([1,2,3])
b = 3*a
print(b)

[3 6 9]


In [5]:
import numpy as np

a = np.array([10,20,30])
b = a/2
print(b)

[ 5. 10. 15.]


### Matrix Multiplication

Numpy array can be multiplied by each other using matrix multiplication. These matrix multiplication methods include element-wise multiplication, the dot product and the cross product

#### Element-wise multiplication

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b

array([ 4, 10, 18])

#### Dot Product

In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

32

#### Cross Product

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.cross(a, b)

array([-3,  6, -3])

### Exponents and Logarithms

```
np.exp()
np.log() - natural log
np.log2() base-2 log
np.log10() base 10 log
np.e
```

### Trigonometry


```
sin()
cos()
tan()
arcsin()
arccos()
arctan()
hypot() Given the sides of a right triangle, returns the hypotenuse.

degrees()
radians()
deg2rad()
rad2deg()
```