## Array Slicing

Multiple values stored within an array can be accessed simultaneously with array _slicing_. To pull out a section or slice of an array, the colon operator ```:``` is used when calling the index. The general form is:

```
<slice> = <array>[start:end+1]
```

Where ```<slice>``` is the slice or section of the array object ```<array>```. The index of the slice is specified in ```[start:end+1]```. Note that Python counting starts at zero and ends at n+1. To pull the first 2 values out of an array, the indexing operation is ```[0:2]```. An example is below:

In [1]:
import numpy as np

a = np.array([2, 4, 6])
b = a[0:2]
print(b)

[2 4]


A blank stands in for the last index. A slicing opperation ```[1:]``` will pull out the 2nd through last value of an array

In [3]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = a[1:]
print(b)

[4 6 8]


A blank also stands in for the first index. The slicing opperation ```[:3]``` will pull out the 1st through third values of an array

In [4]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = a[:3]
print(b)

[2 4 6]


### Slicing 2D Arrays

2D arrays can be sliced with the general form

```
<slice> = <array>[start_row:end_row+1, start_col:end_col-1]
```

In [7]:
import numpy as np

a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
b = a[0:2, 0:3]
print(b)

[[ 2  4  6]
 [10 20 30]]


Again, a blank represents the first index or the last index. The colon opperator also represents "all". To slice out the first two rows and all columns that code is:

In [1]:
import numpy as np

a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
b = a[:2, :]  #[first two rows, all columns]
print(b)

[[ 2  4  6  8]
 [10 20 30 40]]
